import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	container: {
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		marginVertical: 10,
		marginHorizontal: 10,
		paddingHorizontal: 10,
		paddingVertical: 10,
		borderRadius: 5,
	},
	text: {
		fontSize: 14,
		textAlign: 'center',
	},
	text2: {
		fontSize: 16,
		fontWeight: 'bold',
		textAlign: 'center',
		marginBottom: 10,
	},
	container2: {
		alignItems: 'center',
		backgroundColor: '#e55c5c',
		marginVertical: 10,
		marginHorizontal: 10,
		paddingHorizontal: 10,
		paddingVertical: 10,
		borderRadius: 5,
	},
	text3: {
		fontSize: 16,
		textAlign: 'center',
		fontWeight: 'bold',
		color: '#FFFFFF',
	},
	accept: {
		backgroundColor: '#f24343',
		padding: 10,
		borderRadius: 5,
		alignItems: 'center',
		marginBottom: 10,
	},
	cancel: {
		backgroundColor: '#6fceba',
		padding: 10,
		borderRadius: 5,
		alignItems: 'center',
		marginBottom: 10,
	},
	container3: {
		backgroundColor: '#FFFFFF',
		marginVertical: 10,
		marginHorizontal: 10,
		paddingHorizontal: 10,
		paddingVertical: 10,
		borderRadius: 5,
	},
	buttonContainer: {
		borderRadius: 5,
		flex: 1,
		flexDirection: 'row',
		flexWrap: 'wrap',
		width: '100%',
	},
	button1: {
		borderTopLeftRadius: 5,
		borderBottomLeftRadius: 5,
		backgroundColor: '#6fceba',
		padding: 10,
		alignItems: 'center',
		flexGrow: 1,
		flexBasis: 0,
		flexShrink: 0,
	},
	button1Active: {
		borderTopLeftRadius: 5,
		borderBottomLeftRadius: 5,
		backgroundColor: '#6bb3a4',
		padding: 10,
		alignItems: 'center',
		flexGrow: 1,
		flexBasis: 0,
		flexShrink: 0,
	},
	button2: {
		borderTopRightRadius: 5,
		borderBottomRightRadius: 5,
		backgroundColor: '#6fceba',
		padding: 10,
		alignItems: 'center',
		flexGrow: 1,
		flexBasis: 0,
		flexShrink: 0,
	},
	button2Active: {
		borderTopRightRadius: 5,
		borderBottomRightRadius: 5,
		backgroundColor: '#6bb3a4',
		padding: 10,
		alignItems: 'center',
		flexGrow: 1,
		flexBasis: 0,
		flexShrink: 0,
	},
});

export default styles;
